# Generated by Django 4.1.3 on 2022-12-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerName', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('Team', models.CharField(max_length=50)),
                ('Birthday', models.CharField(max_length=50)),
                ('GameDay', models.CharField(max_length=50)),
                ('InjuryStatus', models.CharField(max_length=50)),
            ],
        ),
    ]
