# Generated by Django 4.1.3 on 2022-12-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Sport',
            field=models.CharField(default='soccer', max_length=50),
            preserve_default=False,
        ),
    ]
